In [1]:
import numpy as np
np.__version__

'1.21.0'

In [2]:
john = [10, 8, 6, 7]
x = np.array(john)

print(type(x))
type(x)

<class 'numpy.ndarray'>


numpy.ndarray

In [3]:
print(x)
x

[10  8  6  7]


array([10,  8,  6,  7])

In [4]:
john = [10, 8, 6, 7]
john = np.array(john) + 1   # john = [i + 1 for i in john]
john

array([11,  9,  7,  8])

## 다차원 배열
* 괄호 개수로 파악하면 됨
* np.array([])는 1차원
* np.array([[]])는 2차원

In [5]:
scores = [[1, 2, 3, 4], 
         [5, 6, 7, 8]]
x = np.array(scores)
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
x.shape

(2, 4)

In [7]:
x.dtype

dtype('int32')

In [8]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y = x.reshape(3, 3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
x = np.arange(0, 16)
x = x.reshape(4, 4)
print(x)
x = x.reshape(2, 4, 2)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [45]:
x = np.array([[1], [2], [3]])
print(x.shape)
x = x.reshape(-1)
x

(3, 1)


array([1, 2, 3])

## 슬라이싱, 인덱싱

In [12]:
x = np.array([4, 5, 6, 7, 8, 9, 0])
x[2] # 인덱싱
print(x)
x = x[1:4] # 슬라이싱
print(x)

[4 5 6 7 8 9 0]
[5 6 7]


In [13]:
x = np.array([[4, 5, 6], [8, 9, 0]])
print(x[0][1:], "\n")
print(x[0, 1:], "\n")

[5 6]
[5 6]


In [47]:
x = np.array([[1, 2, 3], [3, 4, 5]])
print(x, "\n")
print(np.sum(x), "\n")
print(np.sum(x, axis=0), "\n")
print(np.sum(x, axis=1), "\n")
print(np.mean(x), "\n")
print(np.mean(x, axis=0), "\n")
print(np.mean(x, axis=1), "\n")

[[1 2 3]
 [3 4 5]] 

18 

[4 6 8] 

[ 6 12] 

3.0 

[2. 3. 4.] 

[2. 4.] 



In [15]:
x = np.array([1, 2, "3"])
x = x.astype(np.int32)
x

array([1, 2, 3])

## 난수 생성 함수

#### np.random.random()
- [0.0 ~ 1.0) 사이의 랜덤값을 반환하는 함수
- random() == random_sample() == rand()

In [17]:
np.random.random(3)

array([0.72503192, 0.66810975, 0.83976691])

In [18]:
np.random.random((2, 2))

array([[0.92995784, 0.60610727],
       [0.42547401, 0.74718266]])

#### np.random.randn()
- 정규분포 추출

In [19]:
np.random.randn(3, 2)

array([[ 1.44401173,  0.05034961],
       [ 0.06770877,  0.55076804],
       [ 0.90140191, -1.01451979]])

#### np.random.randint()
- 랜덤 정수 추출

In [23]:
print(np.random.randint(1, 100), "\n") # 1부터 100사이에서 1개 추출
print(np.random.randint(1, 100, 3), "\n")
print(np.random.randint(1, 100, (3, 2)), "\n")

60
[96 55 35]
[[74 90]
 [43 59]
 [11 89]]


#### np.random.seed()

In [24]:
x = np.array([[1, 2], 
              [3, 4]])
y = np.array([[5, 6],
              [7, 8]])

In [25]:
x + y

array([[ 6,  8],
       [10, 12]])

In [28]:
print(np.add(x, y), "\n")
print(np.subtract(x, y), "\n")
print(np.divide(x, y), "\n")

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]] 



In [29]:
print(x * y, "\n")   # 원소별 곱
print(np.multiply(x, y), "\n")   # 원소별 곱

[[ 5 12]
 [21 32]] 

[[ 5 12]
 [21 32]] 



In [32]:
print(np.dot(x, y), "\n")   # 행렬 곱
print(np.matmul(x, y), "\n")   # 행렬 곱
print(x @ y, "\n")   # 행렬 곱

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]] 



In [33]:
tmp1 = np.array([1, 2, 3])
tmp2 = np.array([4, 5, 6])
print(np.matmul(tmp1, tmp2), "\n")

32 



## np.argmax()
- 값이 가장 큰 원소의 인덱스를 리턴

In [38]:
x = np.random.randn(5, 4)
x

array([[ 0.47979696,  0.24357433,  0.76006217,  0.02189494],
       [ 0.14934853,  0.8624537 , -0.60047009,  0.4332799 ],
       [ 1.17264812, -0.12560475,  0.18196739, -1.99250228],
       [ 1.09796614, -0.68139805, -0.10836873, -2.15634986],
       [-1.15374806,  0.2332438 , -1.33380529, -0.32761795]])

In [40]:
print(np.argmax(x, axis=0), "\n")
print(np.argmax(x, axis=1), "\n")

[2 1 0 1] 

[2 1 0 0 1] 



## 저장
* savez()

In [42]:
x = np.random.randn(5, 4)
y = np.random.randn(3, 3)
np.savez("mydata.npz", xvar=x, yvar=y)   # "mydata"라는 이름으로 저장(x데이터는 xvar라는 키워드로 저장하며 y데이터는 yvar라는 키워드로 저장)

## 파일 로딩

In [43]:
mydata = np.load("mydata.npz")

In [44]:
x = mydata["xvar"]
print(x, "\n")
y = mydata["yvar"]
print(y, "\n")

[[-0.44739659 -0.77842941 -1.99800919 -1.69547193]
 [ 0.90361779  0.36681767 -0.1669465  -0.38232671]
 [ 0.90008182  0.11353986  0.62361477  0.47144535]
 [-0.47277882 -0.51094101  1.03661013  0.23350599]
 [-1.47417307 -2.02895942  0.16645811 -0.78703326]] 

[[-0.095217   -0.16656779 -1.05229137]
 [ 1.02380957 -0.09799937 -0.82821077]
 [-1.00000538 -0.06510517 -0.69456992]] 

